import { AlertTriangle, Link2, Loader2, Plus, ShieldCheck, ShieldMinus, UserRound, Users } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { bindFeishuIdentity, getIdentityAudits, getManagedIdentities, updateIdentityRole, type IdentityAudit, type IdentityList, type ManagedIdentity } from "../api";
import { PageHeader } from "../components/Layouts";

const auditText: Record<IdentityAudit["action"], string> = { bind_feishu_identity: "绑定为外部用户", promote_internal_identity: "提权为内部用户", downgrade_external_identity: "降级为外部用户" };

export function UsersPage() {
  const [data, setData] = useState<IdentityList | null>(null); const [audits, setAudits] = useState<IdentityAudit[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [showBind, setShowBind] = useState(false); const [feishuId, setFeishuId] = useState(""); const [displayName, setDisplayName] = useState("");
  const [pendingRole, setPendingRole] = useState<{ user: ManagedIdentity; role: "external" | "internal" } | null>(null);
  async function load() { setLoading(true); setError(""); try { const [users, events] = await Promise.all([getManagedIdentities(), getIdentityAudits()]); setData(users); setAudits(events); } catch (caught) { setError(caught instanceof Error ? caught.message : "用户数据读取失败。" ); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function bind(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { await bindFeishuIdentity(feishuId.trim(), displayName.trim()); setShowBind(false); setFeishuId(""); setDisplayName(""); setMessage("飞书身份已绑定，并按安全默认设置为外部用户。" ); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "飞书身份绑定失败。" ); } finally { setBusy(false); } }
  async function applyRole() { if (!pendingRole) return; setBusy(true); setError(""); setMessage(""); try { const result = await updateIdentityRole(pendingRole.user.id, pendingRole.role); setMessage(`${pendingRole.user.display_name || pendingRole.user.feishu_user_id} 已${pendingRole.role === "internal" ? "提权为内部用户" : "降级为外部用户"}${result.audit_recorded ? "，并写入审计。" : "。"}`); setPendingRole(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "身份变更失败。" ); } finally { setBusy(false); } }
  const names = useMemo(() => new Map(data?.users.map((user) => [user.id, user.display_name || user.feishu_user_id]) || []), [data]);
  return <main className="page-content admin-users-page"><PageHeader eyebrow="身份与权限" title="用户管理" description="飞书身份首次绑定默认为外部用户；只有管理员明确授权后才能访问敏感知识。" actions={<button className="primary-action" onClick={() => setShowBind(true)}><Plus size={17} />绑定飞书身份</button>} />
    {error && <div className="config-alert error" role="alert">{error}</div>}{message && <div className="config-alert success" role="status">{message}</div>}
    {loading && !data ? <div className="config-loading"><Loader2 className="spin" />正在读取用户身份</div> : <><section className="user-metric-grid"><article><Users /><span>已绑定身份</span><strong>{data?.total || 0}</strong></article><article><UserRound /><span>外部用户</span><strong>{data?.external || 0}</strong></article><article><ShieldCheck /><span>内部用户</span><strong>{data?.internal || 0}</strong></article></section>
      <section className="users-panel"><div className="section-heading"><div><h2>飞书身份与知识权限</h2><p>服务端权限是安全边界；页面隐藏不能替代权限过滤。</p></div></div>{!data?.users.length ? <div className="users-empty"><Link2 size={28} /><h3>尚未绑定飞书身份</h3><p>绑定后仍默认为外部用户，只能访问公开知识。</p></div> : <div className="users-table-wrap"><table className="users-table"><thead><tr><th>用户</th><th>飞书身份</th><th>绑定状态</th><th>知识权限</th><th>操作</th></tr></thead><tbody>{data.users.map((user) => <tr key={user.id}><td><div className="user-name"><span>{(user.display_name || user.feishu_user_id).slice(0, 1).toUpperCase()}</span><div><strong>{user.display_name || "未设置姓名"}</strong><small>登记人：{user.added_by}</small></div></div></td><td><code>{user.feishu_user_id}</code></td><td><span className="bound-badge"><i />已绑定</span></td><td><span className={`role-badge ${user.role}`}>{user.role === "internal" ? "内部用户" : "外部用户"}</span></td><td><button className={user.role === "internal" ? "downgrade-button" : "promote-button"} onClick={() => setPendingRole({ user, role: user.role === "internal" ? "external" : "internal" })}>{user.role === "internal" ? <ShieldMinus size={15} /> : <ShieldCheck size={15} />}{user.role === "internal" ? "降级" : "提权"}</button></td></tr>)}</tbody></table></div>}</section>
      <section className="users-panel audit-panel"><div className="section-heading"><div><h2>最近身份审计</h2><p>绑定、提权和降级均由服务端记录。</p></div></div>{!audits.length ? <div className="inline-empty">暂无身份变更记录。</div> : <div className="identity-audit-list">{audits.slice(0, 8).map((audit) => <article key={audit.id}><span className={audit.action === "downgrade_external_identity" ? "down" : "up"}>{audit.action === "downgrade_external_identity" ? <ShieldMinus size={16} /> : <ShieldCheck size={16} />}</span><div><strong>{names.get(audit.identity_id) || "飞书身份"} · {auditText[audit.action]}</strong><small>操作人：{audit.actor_id} · {new Date(audit.created_at).toLocaleString("zh-CN")}</small></div></article>)}</div>}</section></>}
    {showBind && <div className="confirm-backdrop"><form className="confirm-dialog identity-dialog" onSubmit={bind} role="dialog" aria-modal="true" aria-labelledby="bind-title"><Link2 /><h2 id="bind-title">绑定飞书身份</h2><p>新身份默认是外部用户，不能访问敏感知识。</p><label>显示名称<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="例如：王小明" /></label><label>飞书用户 ID<input required value={feishuId} onChange={(event) => setFeishuId(event.target.value)} placeholder="例如：ou_xxxxxxxxx" /></label><div><button type="button" className="secondary-button" onClick={() => setShowBind(false)}>取消</button><button className="primary-action" disabled={busy || !feishuId.trim()}>{busy ? "正在绑定" : "确认绑定"}</button></div></form></div>}
    {pendingRole && <div className="confirm-backdrop"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="role-confirm-title"><AlertTriangle /><h2 id="role-confirm-title">确认{pendingRole.role === "internal" ? "提权" : "降级"}？</h2><p>{pendingRole.role === "internal" ? "提权后，该用户可以检索公开与敏感知识。" : "降级后，该用户立即只能访问公开知识，敏感答案、原文和引用都应隐藏。"}本次变更会写入审计。</p><div><button className="secondary-button" onClick={() => setPendingRole(null)}>取消</button><button className={pendingRole.role === "internal" ? "primary-action" : "danger-action"} onClick={() => void applyRole()} disabled={busy}>确认{pendingRole.role === "internal" ? "提权" : "降级"}</button></div></section></div>}
  </main>;
}
